language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"

matrix:
  allow_failures:
    - python: "2.7"

install:
  - pip install nose codecov unittest2
  - python setup.py install

script:
  - "nosetests --with-coverage --cover-package=charset_normalizer test/*.py"

after_success:
  - codecov
